apiVersion: v1
kind: Secret
metadata:
  name: lms-secret
type: Opaque
data:
  secret-key: ZGphbmdvLWluc2VjdXJlLXQ2XjdsX2N4cGJuIWc9QHUyYzJxXz0zQGpwLUBnKXEqYTBlZnlxMWYhXmUzJTZndHkx
  db-password: bG1zX3Bhc3N3b3Jk
  email-password: YmhhYW1lZmxpcGF2aXNjZA==
